name: Build and Deploy Anki Add-on

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Building version: ${VERSION}"
      
      - name: Update version tag in __init__.py
        run: |
          echo "Before replacement:"
          cat better-markdown-anki/__init__.py
          
          sed -i 's/TAG = "DEV_TAG"/TAG = "${{ steps.extract_version.outputs.version }}"/g' better-markdown-anki/__init__.py
          
          echo "After replacement:"
          grep "TAG =" better-markdown-anki/__init__.py
      
      - name: Create add-on package
        run: |
          cd better-markdown-anki
          zip -r ../better-markdown-anki-${{ steps.extract_version.outputs.version }}.ankiaddon *
          cd ..
          
          echo "Package created:"
          ls -la *.ankiaddon
      
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: better-markdown-anki-${{ steps.extract_version.outputs.version }}.ankiaddon
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
